"""Measure shipped sprite alpha for runtime anchors. No image manipulation.

Requires Pillow. Run from any directory after replacing a zombie atlas.
"""
from pathlib import Path
import json
import re
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
IMAGES = ROOT / "assets/images"


def measure(image):
    alpha = image.convert("RGBA").getchannel("A")
    weight = sx = sy = 0
    for index, a in enumerate(alpha.tobytes()):
        if a > 8:
            weight += a
            sx += (index % image.width + 0.5) * a
            sy += (index // image.width + 0.5) * a
    box = alpha.point(lambda a: 255 if a > 8 else 0).getbbox()
    return {
        "x": round(sx / weight / image.width - 0.5, 4),
        "y": round(sy / weight / image.height - 0.5, 4),
        "width": round((box[2] - box[0]) / image.width, 4),
        "height": round((box[3] - box[1]) / image.height, 4),
    }


def frames(image, width, height=None):
    height = height or width
    return [measure(image.crop((x, y, x + width, y + height)))
            for y in range(0, height * (image.height // height), height)
            for x in range(0, width * (image.width // width), width)]


data = {"walk": {}, "death": {}}
final = {}
for path in sorted(IMAGES.glob("zombie-walk-*.png")):
    with Image.open(path) as image:
        data["walk"][path.stem.replace("zombie-walk-", "")] = [
            [m["x"], m["y"]] for m in frames(image, image.width // 4, image.height // 4)]
for path in sorted(IMAGES.glob("zombie-death-*-sheet.png")):
    # Legacy, unregistered death sheets are not part of the runtime atlas set.
    game = (ROOT / "js/game.js").read_text(encoding="utf-8")
    if f'"{path.stem}"' not in game:
        continue
    with Image.open(path) as image:
        measured = frames(image, 512)
    data["death"][path.stem] = [[m["x"], m["y"]] for m in measured]
    final[path.stem] = measured[-1]

lines = ["// Generated by scripts/measure-zombie-motion.py; alpha threshold > 8.",
         "(function (global) {", "  const data = {"]
for group, entries in data.items():
    lines.append(f"    {group}: {{")
    for key, value in entries.items():
        lines.append(f"      {json.dumps(key)}: {json.dumps(value, separators=(',', ':'))},")
    lines.append("    },")
lines.extend(["  };", "  if (typeof module !== 'undefined' && module.exports) module.exports = data;",
              "  global.SchoolZombieMotionData = data;", "})(typeof globalThis !== 'undefined' ? globalThis : this);", ""])
(ROOT / "js/zombie-motion-data.js").write_text("\n".join(lines), encoding="utf-8")
block = "const ZOMBIE_DEATH_FINAL_FRAME_BOUNDS = {\n"
for key, m in final.items():
    block += f'    "{key}": {{ x: {m["x"]}, y: {m["y"]}, width: {m["width"]}, height: {m["height"]} }},\n'
block = block.rstrip(",\n") + "\n  };"
game = (ROOT / "js/game.js").read_text(encoding="utf-8")
game = re.sub(r"const ZOMBIE_DEATH_FINAL_FRAME_BOUNDS = \{.*?\n  \};", block, game, flags=re.S)
(ROOT / "js/game.js").write_text(game, encoding="utf-8")
print(f'Measured {len(data["walk"])} walk atlases and {len(data["death"])} death atlases')
