// Generated by scripts/install_higgsfield_character_vfx_20260716.py.
// Bounds use alpha >= 12 on the 512x512 peak sprite and drive hit-range fitting.
export const COMBAT_VFX_CANVAS_SIZE = 512;

export const COMBAT_VFX_VISIBLE_BOUNDS = Object.freeze({
    'basic_attack_shadow_dagger_slash': Object.freeze({ left: 86, top: 234, right: 426, bottom: 277, width: 340, height: 43 }),
    'char_skill_shadow_dagger': Object.freeze({ left: 57, top: 185, right: 456, bottom: 326, width: 399, height: 141 }),
    'char_skill_shadow_slash': Object.freeze({ left: 20, top: 20, right: 492, bottom: 491, width: 472, height: 471 }),
    'char_skill_rulers_authority': Object.freeze({ left: 46, top: 21, right: 465, bottom: 489, width: 419, height: 468 }),
    'char_skill_dragon_fear': Object.freeze({ left: 28, top: 21, right: 484, bottom: 492, width: 456, height: 471 }),
    'basic_attack_light_sword_slash': Object.freeze({ left: 185, top: 117, right: 406, bottom: 296, width: 221, height: 179 }),
    'char_skill_light_lance_pierce': Object.freeze({ left: 54, top: 36, right: 457, bottom: 476, width: 403, height: 440 }),
    'char_skill_light_crescent': Object.freeze({ left: 35, top: 42, right: 492, bottom: 412, width: 457, height: 370 }),
    'char_skill_light_judgment': Object.freeze({ left: 73, top: 20, right: 453, bottom: 488, width: 380, height: 468 }),
    'char_skill_light_sanctum': Object.freeze({ left: 45, top: 27, right: 492, bottom: 438, width: 447, height: 411 }),
    'basic_attack_tiger_claw_swipe': Object.freeze({ left: 123, top: 127, right: 378, bottom: 384, width: 255, height: 257 }),
    'char_skill_tiger_fang_combo': Object.freeze({ left: 63, top: 20, right: 448, bottom: 492, width: 385, height: 472 }),
    'char_skill_tiger_rend': Object.freeze({ left: 41, top: 24, right: 489, bottom: 492, width: 448, height: 468 }),
    'char_skill_tiger_quake': Object.freeze({ left: 20, top: 22, right: 492, bottom: 490, width: 472, height: 468 }),
    'char_skill_tiger_guard': Object.freeze({ left: 44, top: 37, right: 458, bottom: 469, width: 414, height: 432 }),
    'basic_attack_flame_fireball': Object.freeze({ left: 227, top: 199, right: 278, bottom: 238, width: 51, height: 39 }),
    'char_skill_flame_bolt': Object.freeze({ left: 55, top: 36, right: 474, bottom: 419, width: 419, height: 383 }),
    'char_skill_flame_arc': Object.freeze({ left: 36, top: 20, right: 492, bottom: 471, width: 456, height: 451 }),
    'char_skill_flame_meteor': Object.freeze({ left: 125, top: 20, right: 466, bottom: 483, width: 341, height: 463 }),
    'char_skill_flame_inferno': Object.freeze({ left: 44, top: 20, right: 488, bottom: 463, width: 444, height: 443 }),
    'basic_attack_sanctuary_mace_slam': Object.freeze({ left: 132, top: 96, right: 416, bottom: 383, width: 284, height: 287 }),
    'char_skill_sanctuary_pulse': Object.freeze({ left: 48, top: 53, right: 466, bottom: 465, width: 418, height: 412 }),
    'char_skill_sanctuary_arc': Object.freeze({ left: 84, top: 20, right: 477, bottom: 434, width: 393, height: 414 }),
    'char_skill_sanctuary_seal': Object.freeze({ left: 65, top: 20, right: 487, bottom: 454, width: 422, height: 434 }),
    'char_skill_sanctuary_field': Object.freeze({ left: 42, top: 23, right: 492, bottom: 460, width: 450, height: 437 }),
});

const DEFAULT_BOUNDS = Object.freeze({
    left: 0, top: 0, right: COMBAT_VFX_CANVAS_SIZE, bottom: COMBAT_VFX_CANVAS_SIZE,
    width: COMBAT_VFX_CANVAS_SIZE, height: COMBAT_VFX_CANVAS_SIZE,
});

export function getCombatVfxVisibleBounds(textureKey) {
    const identity = String(textureKey || '').replace(/_\d+$/, '');
    return COMBAT_VFX_VISIBLE_BOUNDS[identity] || DEFAULT_BOUNDS;
}
